name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Dear Contributor,

          Welcome aboard! Your contribution to our project is deeply appreciated. Thank you for sharing your skills and dedication. Together, let's make a difference!

          Warm regards,
          Developers-Kuno
        pr-message: |
          Dear Contributor,

          Welcome aboard! Your contribution to our project is deeply appreciated. Thank you for sharing your skills and dedication. Together, let's make a difference!

          Warm regards,
          Developers-Kuno
